main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: /research/
    weight: 20
  - name: Publications
    url: /publications/
    weight: 30
  - name: Openings
    url: /openings/
    weight: 50
  - name: CV
    url: /cv/
    weight: 60
  - name: Contact
    url: /contact/
    weight: 70
