############################
## HUGO MODULES
############################

imports:
  - path: github.com/HugoBlox/kit/modules/integrations/netlify
  - path: github.com/HugoBlox/kit/modules/blox

mounts:
  - source: hugo-blox/blox/community
    target: layouts/_partials/blox/community/
    files: '**.html'
  - source: hugo-blox/blox/all-access
    target: layouts/_partials/blox/
    files: '**.html'
  - source: hugo-blox/blox
    target: assets/dist/community/blox/
    files: '**.css'
  - source: layouts
    target: layouts
  - source: assets
    target: assets
